In [21]:
import numpy as np
import scipy as linalg
from scipy import linalg

In [22]:
A = np.array([[1, 3, 5], [2, 5, 1], [2, 3, 8]])


In [23]:
A

array([[1, 3, 5],
       [2, 5, 1],
       [2, 3, 8]])

In [24]:
b = np.array([[10], [8], [3]])


In [25]:
b

array([[10],
       [ 8],
       [ 3]])

## multiplaycation

In [28]:
np.linalg.solve(A, b)

array([[-9.28],
       [ 5.16],
       [ 0.76]])

## Let's valiate the result

In [27]:
A.dot(linalg.inv(A).dot(b)) - b

array([[ 0.],
       [ 0.],
       [ 0.]])