In [5]:
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np

load data

In [25]:
iris = load_iris()

In [7]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)

In [8]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [9]:
df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)

In [10]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

creating training and test data

In [13]:
df['is_train'] = np.random.uniform(0, 1, len(df)) <= .75

In [14]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species is_train  
0  setosa    False  
1  setosa    False  
2  setosa     True  
3  setosa    False  
4  setosa     True

In [15]:
train, test = df[df['is_train']==True], df[df['is_train']==False]

In [16]:
print('Number of observations in the trainin data:', len(train))

Number of observations in the trainin data: 116


In [22]:
print('Number of obervation in the test data:, len(test)')

Number of obervation in the test data:, len(test)


preprocess data


In [18]:
features = df.columns[:4]
features

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [19]:
y = pd.factorize(train['species'])[0]

In [20]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2], dtype=int64)

train the random forest classifier

In [27]:
clf = RandomForestClassifier(n_jobs = 2)

In [28]:
clf.fit(train[features], y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=2, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

apply classifier to test data

In [29]:
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 1, 1, 1, 2], dtype=int64)

In [30]:
clf.predict_proba(test[features])[0:10]

array([[ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.]])

evaluate classifier

In [31]:
preds = iris.target_names[clf.predict(test[features])]

In [32]:
preds[0:5]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa'], 
      dtype='<U10')

In [33]:
test['species'].head()

0     setosa
1     setosa
3     setosa
9     setosa
11    setosa
Name: species, dtype: category
Categories (3, object): [setosa, versicolor, virginica]

create a confusion matrix

In [34]:
pd.crosstab(test['species'], preds, rownames=['actual sepcies'], colnames=['predicted species'])

predicted species  setosa  versicolor  virginica
actual sepcies                                  
setosa                 13           0          0
versicolor              0          12          0
virginica               0           3          6

view feature importance

In [36]:
list(zip(train[features], clf.feature_importances_))

[('sepal length (cm)', 0.062935208811071924),
 ('sepal width (cm)', 0.029035840390380107),
 ('petal length (cm)', 0.44906762203133005),
 ('petal width (cm)', 0.45896132876721801)]