In [1]:
import numpy as np

In [7]:
a = np.array([[1, 2, 7], [3, 4, 8], [5, 6, 9]])

In [8]:
a

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

In [9]:
a.transpose()

array([[1, 3, 5],
       [2, 4, 6],
       [7, 8, 9]])

In [13]:
a.transpose(0, 1)

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])